In [35]:
#Optional Task 20: Session 20 (AIML) - Assignment Questions

In [ ]:
import pandas as pd

In [37]:
df = pd.read_csv("insurance.csv")

In [38]:
#Q.1

X = df.drop("expenses", axis=1)
y = df["expenses"]

In [39]:
print("Shape of X:", X.shape)
print("Shape of y:", y.shape)

Shape of X: (1338, 6)
Shape of y: (1338,)

In [40]:
#Q.2

categorical_cols = X.select_dtypes(include=["object"]).columns
print(categorical_cols)

Index(['sex', 'smoker', 'region'], dtype='str')

C:\Users\Shree\AppData\Local\Temp\ipykernel_18032\591317781.py:3: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  categorical_cols = X.select_dtypes(include=["object"]).columns

In [41]:
X_encoded = pd.get_dummies(X, columns=categorical_cols).astype(int)

In [42]:
X_encoded.head()

,age,bmi,children,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,19,27,0,1,0,0,1,0,0,0,1
1,18,33,1,0,1,1,0,0,0,1,0
2,28,33,3,0,1,1,0,0,0,1,0
3,33,22,0,0,1,1,0,0,1,0,0
4,32,28,0,0,1,1,0,0,1,0,0

In [43]:
#Q.3

from sklearn.preprocessing import StandardScaler

In [44]:
numerical_cols = ["age", "bmi", "children"]

scaler = StandardScaler()
X_encoded[numerical_cols] = scaler.fit_transform(X_encoded[numerical_cols])

In [45]:
X_encoded.head()

,age,bmi,children,sex_female,sex_male,smoker_no,smoker_yes,region_northeast,region_northwest,region_southeast,region_southwest
0,-1.438764,-0.524492,-0.908614,1,0,0,1,0,0,0,1
1,-1.509965,0.457692,-0.078767,0,1,1,0,0,0,1,0
2,-0.797954,0.457692,1.580926,0,1,1,0,0,0,1,0
3,-0.441948,-1.342979,-0.908614,0,1,1,0,0,1,0,0
4,-0.513149,-0.360795,-0.908614,0,1,1,0,0,1,0,0

In [46]:
#Q.4

from sklearn.model_selection import train_test_split

In [47]:
X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y,
    test_size=0.33,
    random_state=42
)

In [48]:
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (896, 11)
X_test: (442, 11)
y_train: (896,)
y_test: (442,)

In [49]:
#Q.5

from sklearn.linear_model import LinearRegression

In [50]:
print("Intercept:", model.intercept_)
print("Coefficients:")
print(model.coef_)

Intercept: 20282.060983682026
Coefficients:
[  3670.51864053   2107.17223864    448.6441635     -61.06322975
     61.06322975 -11851.63429707  11851.63429707    502.66722849
    171.10771497   -380.99258705   -292.7823564 ]

In [51]:
#Q.6

y_pred = model.predict(X_test)

In [52]:
comparison = pd.DataFrame({
    "Actual": y_test.values[:10],
    "Predicted": y_pred[:10]
})

comparison

     Actual     Predicted
0   9095.07   8927.892380
1   5272.18   7224.306120
2  29330.98  36865.489023
3   9301.89   9352.110400
4  33750.29  26951.769637
5   4536.26  10871.419631
6   2117.34     21.928132
7  14210.54  17078.670330
8   3732.63    980.902835
9  10264.44  11170.961772

In [53]:
#Q.7

from sklearn.metrics import r2_score

In [54]:
r2 = r2_score(y_test, y_pred)
print("R² Score:", r2)

R² Score: 0.7607883096893395

In [55]:
print(f"The model explains {r2*100:.2f}% of the variation in insurance expenses.")
print("Higher R² means better prediction performance.")

The model explains 76.08% of the variation in insurance expenses.
Higher R² means better prediction performance.

In [56]:
#Q.8

import joblib

In [57]:
print(joblib.dump(model, "LR_insurance.pkl"))
print(joblib.dump(scaler, "scaler.pkl"))
print(joblib.dump(X_encoded.columns.tolist(), "columns.pkl"))

['LR_insurance.pkl']
['scaler.pkl']
['columns.pkl']

In [58]:
print("Model saved as LR_insurance.pkl")
print("Scaler saved as scaler.pkl")
print("Columns saved as columns.pkl")

Model saved as LR_insurance.pkl
Scaler saved as scaler.pkl
Columns saved as columns.pkl